### ISSUE TITLE
Storage Bucket Permission Error

### ISSUE THREAD

**Issue by djperrefort** [mwvgroup/Pitt-Google-Broker#12]
After following the installation instructions and importing the `broker` package, I get the following error message in GCP:

> #### Log Export Destination
>    storage.googleapis.com/ardent-cycling-243415_logging_bucket
>
> #### Error Code
>     bucket_permission_denied
> 
> #### Error Detail
>   The specified storage bucket does not allow the service account associated with the log sink to create objects in it. Grant create permission for the service account specified in the sink's `writerIdentity `field on the storage bucket.
> 
>   Please fix this error by following steps documented in troubleshooting logging exports. If the sink is no longer needed, it can be quickly removed using gcloud: gcloud logging sinks delete logging_sink --project=ardent-cycling-243415

Looking into this I found the following in the ["Exporting with the Logs Viewer"](https://cloud.google.com/logging/docs/export/configure_export_v2#dest-auth) documentation:

> When you create a sink, Logging creates a new service account for the sink, called a unique writer identity. You cannot manage this service account directly as it is owned and managed by Stackdriver Logging. The service account is deleted if the sink gets deleted. Your export destination must permit this service account to write log entries.

Apparently, this is supposed to happen automatically but for some reason didn't:

> If you created your sink in the GCP Console and you have Owner access to the destination, then Stackdriver Logging should have set up the necessary permissions on your behalf.

To resolve this issue we need to:

- [ ] Assign the appropriate logging permissions manually (Which is good practice anyways since not all deployments will necessarily have Owner access)
- [ ] Update the installation instructions to include setting the logging permissions.

**Comment by troyraen** [comment]
Another issue has arisen with this particular logging sink. Starting Dec 15, 2020 we started getting emails stating that the GCS bucket `storage.googleapis.com/ardent-cycling-243415_logging_bucket` can't be found:

> Error in Cloud Logging Export Configuration
> 
> The following log sink in a project you own had errors while exporting logs. Due to this error, logs are not being exported to the sink destination.
> 
> Project ID
> ardent-cycling-243415
> 
> Log Export Sink Name
> logging_sink
> 
> Log Export Destination
> storage.googleapis.com/ardent-cycling-243415_logging_bucket
> 
> Error Code
> bucket_not_found
> 
> Error Detail
> The specified storage bucket could not be found by the Cloud Logging service. Create the bucket and grant object create permission for the service account specified in the sink's writerIdentity field on the bucket. You can also set up Cloud Logging to use a different destination.
> 
> Please fix this error by following steps documented in troubleshooting logging exports. If the sink is no longer needed, it can be quickly removed using gcloud: gcloud logging sinks delete logging_sink --project=ardent-cycling-243415

I am not aware of, nor could I find, any recent changes to this bucket or log sink; I don't know why it's suddenly throwing this error.

@djperrefort I'm not sure why this was set up in the first place or whether we actually need it. For now I have simply disabled this log sink. Let me know if this is something we actually need.

**Comment by djperrefort** [comment]
Closing as no longer relevant.
