### ISSUE TITLE
VM startup script exits due to bug, also unable to set VM metadata (main/elasticc branch)

### ISSUE THREAD

**Issue by hernandezc1** [mwvgroup/Pitt-Google-Broker#206]
At the beginning of `vm_startup.sh`, line 7 (`rm -rf "${brokerdir}"`) deletes the specified directory and its contents in order to start fresh. This is causing the startup script to exit after executing line 8: `cd "${workingdir}" || exit` because the directory `/home/broker` does not exist. See screenshot below:

![bug](https://github.com/mwvgroup/Pitt-Google-Broker/assets/83978600/859a39d2-16f1-4439-ad4c-4cedc6e8e7a6)

The source of the issue is that before PR #205  was merged into `main/elasticc`, the pitt-reader.user.keytab (`/home/broker/pitt-reader.user.keytab`) was made immutable. As a result, after running line 7, the directory `/home/broker` was not deleted because `pitt-reader.user.keytab` could not be removed. Since we've now deleted the `pitt-reader.user.keytab` file as a result of PR #205, the command in line 7 now deletes the directory.

After manually going through the rest of `vm_startup.sh`, I also noticed an error message when trying to set the VM metadata (lines 53-54). See the screenshot below:

![Screenshot 2023-10-12 at 6 25 46 PM](https://github.com/mwvgroup/Pitt-Google-Broker/assets/83978600/249d0633-b28a-41fe-9a14-7bd8a0faf068)

The message points me to two websites: [gcloud topic flags-file](https://cloud.google.com/sdk/gcloud/reference/topic/flags-file) and [gcloud topic escaping](https://cloud.google.com/sdk/gcloud/reference/topic/escaping). I tried implementing the suggestions provided in the second link, but I unfortunately kept getting the same error message.

I will continue to work on this issue tomorrow and provide additional updates.

**Comment by troyraen** [comment]
Looks like there's really 2 issues here:

1. The script exits early because `workingdir` doesn't exist.
2. The syntax for setting VM instance metadata needs to be different when a key/value pair includes commas.

My thoughts:

1. Script exits early:
    - Move line 7 (`rm -rf "${brokerdir}"`) down to line 42 so that it happens right before the fresh files get downloaded.
    - Let's also avoid the `cd` altogether:
        - Delete line 8 (`cd "${workingdir}" || exit`)
        - Rename the `workingdir` to `consumerdir` for clarity (find and replace all occurrences in the file). 
        - Anywhere that relies on being in the old `workingdir` should be given the full path to `consumerdir`. This includes lines 57 and 63 (defining an `fconfig` variable) and maybe others that I missed at first glance.

2. Metadata syntax:
    - I'm not sure what you tried, but my reading of the links you posted is that lines 53 and 54 need to change to this:

```
gcloud compute instances add-metadata "${consumerVM}" --zone "${zone}" \
    --metadata ^:^CURRENT_PS_TOPIC=${PS_TOPIC}:CURRENT_KAFKA_TOPIC=${KAFKA_TOPIC}
```

I think right now we're not setting the list of Kafka topics as VM metadata anywhere else in the code. So we just need to keep this in mind if/when we want to do something like this in the future.

**Comment by hernandezc1** [comment]
Thank you for your feedback.

I've opened up PR #207 to address these issues. A few things I'd like to point out:

The command `rm -rf "${brokerdir}"` will still delete the broker directory. This will cause an error when trying to download the fresh config files from the bucket:

<img width="882" alt="Screenshot 2023-10-13 at 7 23 12 AM" src="https://github.com/mwvgroup/Pitt-Google-Broker/assets/83978600/1ab6accf-9583-4bd0-861e-cbd58992f7c9">

I suggest creating the broker directory `mkdir "${brokerdir}"` to address this.

<img width="887" alt="Screenshot 2023-10-13 at 9 08 43 AM" src="https://github.com/mwvgroup/Pitt-Google-Broker/assets/83978600/92368e4d-4064-4d07-abe7-86b0baff3d7e">

Another issue: in order to set the connector's configs (project and topics), we will either have to cd into the consumer directory or specify the full path to the file. Otherwise, we get the following error message:

<img width="821" alt="Screenshot 2023-10-13 at 8 37 02 AM" src="https://github.com/mwvgroup/Pitt-Google-Broker/assets/83978600/7c390252-939c-4f2f-b7b3-301eefea66e0">

Since we want to avoid cd'ing altogether, I've updated the code so that it specifies the full path for the file.

I'd appreciate your feedback on these suggestions. PR #207 is ready for review, and code changes have been successfully tested.

**Comment by troyraen** [comment]
> I suggest creating the broker directory mkdir "${brokerdir}"

That'll work. Another option would be to delete everything under that directory but not the directory itself.

> in order to set the connector's configs (project and topics), we will either have to cd into the consumer directory or specify the full path to the file... Since we want to avoid cd'ing altogether, I've updated the code so that it specifies the full path for the file.

Yes, that was my last suggestion for this issue:

> Anywhere that relies on being in the old workingdir should be given the full path to consumerdir. This includes lines 57 and 63 (defining an fconfig variable)

**Comment by hernandezc1** [comment]
I should've caught this, I apologize.

> Yes, that was my last suggestion for this issue:

**Comment by troyraen** [comment]
No worries. Good that you did catch it by directly looking at/testing the file.
